# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RatioSet.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import QDialog


class Ui_ParameterSettingDialog(QDialog):
    def __init__(self, info, threshold, unit):
        super(Ui_ParameterSettingDialog, self).__init__()
        self.setupUi(self)
        self.init(self)
        self.label.setText(info)
        self.label_2.setText(unit)
        self.horizontalSlider.setRange(0, threshold)
        self.spinBox.setRange(0, threshold)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(298, 128)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 201, 16))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 50, 261, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ratio set"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "Set a PrbABS6 ratio"))
        self.label_2.setText(_translate("Dialog", "%"))

    def init(self, Dialog):
        self.horizontalSlider.setRange(0, 100)
        self.spinBox.valueChanged.connect(self.horizontalSlider.setValue)
        self.horizontalSlider.valueChanged.connect(self.spinBox.setValue)
        self.pushButton.clicked.connect(Dialog.accept)

    @staticmethod
    def getResult():
        print(1)
        dialog = Ui_ParameterSettingDialog()
        result = dialog.exec_()
        value = float(dialog.horizontalSlider.value())
        if dialog.label_2.text() == '%':
            value /= 100
        return result,  value
